namespace Acne.Hello.Plataform.Generic.Domain.Model.Entities;
/// <summary>
/// Represents a Developer entity in the generica bounded context with an autogenerated ID
/// And trimer first and last name
/// </summary>
public class Developer
{
    /// <summary>
    /// Initializes a new instance of the Developer entity with trimed names 
    /// </summary>
    /// <param name="firstName">The developer's first name 
    /// </param>
    /// <param name="lastName"> the developer last name</param>
    public Developer(string firstName, string lastName)
    {
        FirstName = string.IsNullOrWhiteSpace(firstName) ? string.Empty : firstName.Trim();
        LastName = string.IsNullOrWhiteSpace(lastName) ? string.Empty : lastName.Trim();
    }
/// <summary>
/// Returns the full name by concatenating first and last name with a space
/// </summary>
/// <returns>the full name of the developer</returns>
    public string GetFullName() => $"{FirstName} {LastName}";
    /// <summary>
    /// Checks either the first name or the last name is empty after triming 
    /// </summary>
    /// <returns> true if either name is empty; otherwise, false. </returns>
    public bool IAnyNameEmpty()=> string. IsNullOrEmpty(FirstName) || string.IsNullOrEmpty(LastName);
    public Guid Id { get; }=Guid.NewGuid();
    public string FirstName { get; }
    public string LastName { get; }
    
    
}